### ISSUE TITLE
找到一个更好的演示框架

### ISSUE THREAD

**Issue by dongrentianyu** [tiddly-gittly/flow-chart#8]
https://github.com/zhangyuanliang/flowchart-vue

下面是在线网址

https://zhangyuanliang.github.io/flowchart/flowchart.html

感觉这个挺有意思。

**Comment by linonetwo** [comment]
这也是 fbp，而不是白板，而且才几百星的我不用，至少也要 noflo 那样的

**Comment by dongrentianyu** [comment]
那或者看看这个https://github.com/didi/LogicFlow

我跟whitefall打算把这个包装成插件。

**Comment by dongrentianyu** [comment]
这是仓库链接https://github.com/Zacharia2/reasonflow

我们打算等做出来再放到社区里去。
